# Generated by Django 2.0.2 on 2018-03-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254, verbose_name='Your email address')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('content', models.TextField(max_length=1000, verbose_name='Content')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
