# Generated by Django 2.0.1 on 2018-01-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default='2017-01-01 12:12:12'),
            preserve_default=False,
        ),
    ]
