# Generated by Django 2.2.5 on 2019-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.CharField(blank=True, choices=[('author', 'author ascending'), ('title', 'title ascending'), ('created_date', 'created date ascending'), ('modified_date', 'modified date ascending'), ('-author', 'author descending'), ('-title', 'title descending'), ('-created_date', 'created date descending'), ('-modified_date', 'modified date descending')], max_length=15, null=True),
        ),
    ]
