# Generated by Django 2.0.1 on 2018-03-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='_file',
            new_name='data',
        ),
    ]
