# Generated by Django 2.2.5 on 2019-09-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.CharField(blank=True, choices=[('title', 'title ascending'), ('created_date', 'created date ascending'), ('modified_date', 'modified date ascending'), ('-title', 'title descending'), ('-created_date', 'created date descending'), ('-modified_date', 'modified date descending')], max_length=15, null=True),
        ),
    ]
