# Generated by Django 2.0 on 2017-12-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='group',
            name='classes',
            field=models.ManyToManyField(blank=True, to='timetable.Class'),
        ),
    ]
