# Generated by Django 2.0.2 on 2018-04-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitution',
            name='room',
        ),
    ]
