# Generated by Django 2.0.1 on 2018-03-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='period',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='period',
            field=models.IntegerField(),
        ),
    ]
