# Generated by Django 2.0.6 on 2018-12-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='period',
            new_name='period_number',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='period',
            new_name='period_number',
        ),
        migrations.RenameField(
            model_name='substitution',
            old_name='period',
            new_name='period_number',
        ),
    ]
