# Generated by Django 2.0 on 2018-01-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_substitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('groups', models.ManyToManyField(to='timetable.Group')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='substitution',
            name='group',
        ),
    ]
