# Generated by Django 2.0.6 on 2018-10-23 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20180906_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='link_to_class',
            field=models.BooleanField(default=False),
        ),
    ]
