# Generated by Django 2.2.5 on 2019-09-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20181228_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=17),
        ),
    ]
