# Generated by Django 2.0.1 on 2018-03-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20180307_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='is_default',
            field=models.NullBooleanField(default=None, unique=True),
        ),
    ]
