# Generated by Django 2.2.28 on 2023-02-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20190902_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.Room'),
        ),
    ]
