# Generated by Django 2.0.1 on 2018-02-20 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20180220_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitution',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='timetable.Group'),
            preserve_default=False,
        ),
    ]
