# Generated by Django 2.0.1 on 2018-02-20 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_substitution_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='substitution',
            name='group',
        ),
        migrations.AddField(
            model_name='substitution',
            name='substitute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.Teacher'),
        ),
        migrations.AlterField(
            model_name='substitution',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='timetable.Teacher'),
        ),
    ]
