# Generated by Django 2.0.2 on 2018-02-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_auto_20180220_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='groups',
        ),
        migrations.AddField(
            model_name='absence',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='timetable.Group'),
            preserve_default=False,
        ),
    ]
