# Generated by Django 4.2.28 on 2026-08-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0008_alter_absence_id_alter_class_id_alter_dayplan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sport', models.CharField(max_length=40)),
                ('class_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_class_one', to='timetable.class')),
                ('class_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_class_two', to='timetable.class')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
